#!/bin/bash
#time:20170315

. /etc/init.d/functions
FILE_PATH=/etc/openvpn_authfile.conf
[ ! -f $FILE_PATH ] && touch $FILE_PATH
usage() {
    cat <<eof
    USAGE: `basename $0` {-add|-del|-search} username
eof
}

#judge run user
if [ $UID -ne 0 ];then
    echo "You are not super user,please call root."
    exit 1
fi

#judge arg numbers
if [ $# -ne 2 ];then
   usage
   exit 1
fi

case $1 in 
    -a|-add)
        shift		#==将$1清除，将$2替换为$1,位置参数左移
	if grep "^$1$" ${FILE_PATH} >/dev/null 2>&1;then #过滤命令行第一个参数的值
	    action $"vpnuser,$1 is exist"  /bin/false
	else
	    chattr -i ${FILE_PATH}
	    /bin/cp ${FILE_PATH} ${FILE_PATH}.$(date +%F%T)	
	    echo "$1" >> ${FILE_PATH}
	    [ $? -eq 0 ] && action $"Add $1" /bin/true
	    chattr +i ${FILE_PATH}
	fi
	;;
    -d|-del)
	shift
	if [ `grep "\b$1\b" ${FILE_PATH}|wc -l` -lt 1 ];then
	    action $"vpnuser,$1 is not exist." /bin/false
	    exit
	else
	    chattr -i ${FILE_PATH}
	    /bin/cp ${FILE_PATH} ${FILE_PATH}.$(date +%F%T)
	    sed -i "/^${1}$/d" ${FILE_PATH}
	    [ $? -eq 0 ] && action $"Del $1" /bin/true
	    chattr +i ${FILE_PATH}
	    exit
	fi
	;;
    -s|search)
	shift
	if [ `grep -w $1 ${FILE_PATH}|wc -l` -lt 1 ];then
	    echo $"vpnuser,$1 is not exist.";exit
	else
	    echo $"vpnuser,$1 is exist.";exit
 	fi
	;;
    *)
	usage
	exit
	;;
esac
